DIR_GIT = ".git"

FILE_EXTENSION_ENV = "env"
FILE_EXTENSION_PYTHON = "py"
FILE_EXTENSION_YAML = "yml"

FILE_NAME_ENV = f".{FILE_EXTENSION_ENV}"
FILE_NAME_ENV_YAML = f".{FILE_EXTENSION_ENV}.{FILE_EXTENSION_YAML}"

PATH_NAME_PATH = 'path'
PATH_NAME_FILE = 'file'
PATH_NAME_DIRECTORY = 'directory'